//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comp1004_assignment4_200180985.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public short productID { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string manufacturer { get; set; }
        public string model { get; set; }
        public string RAM_type { get; set; }
        public string RAM_size { get; set; }
        public string displaytype { get; set; }
        public string screensize { get; set; }
        public string resolution { get; set; }
        public string CPU_Class { get; set; }
        public string CPU_brand { get; set; }
        public string CPU_type { get; set; }
        public string CPU_speed { get; set; }
        public string CPU_number { get; set; }
        public string condition { get; set; }
        public string OS { get; set; }
        public string platform { get; set; }
        public string HDD_size { get; set; }
        public string HDD_speed { get; set; }
        public string GPU_Type { get; set; }
        public string optical_drive { get; set; }
        public string Audio_type { get; set; }
        public string LAN { get; set; }
        public string WIFI { get; set; }
        public string width { get; set; }
        public string height { get; set; }
        public string depth { get; set; }
        public string weight { get; set; }
        public string moust_type { get; set; }
        public string power { get; set; }
        public string webcam { get; set; }
    }
}
